# Generated by Django 5.0 on 2023-12-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('role', models.CharField(max_length=25)),
                ('property_name', models.CharField(max_length=255)),
                ('property_management_company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('building_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('floors', models.BigIntegerField()),
                ('total_units', models.BigIntegerField()),
                ('year_of_built', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('descriptiom', models.CharField()),
                ('neighbourhood', models.CharField(max_length=255)),
                ('thumbnail', models.CharField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiibs_backend.users')),
            ],
        ),
    ]
