# Generated by Django 5.0 on 2023-12-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiibs_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('linked_id', models.BigIntegerField()),
                ('media_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='buildings',
            old_name='neighbourhood',
            new_name='neighbourhood_name',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='descriptiom',
        ),
        migrations.AddField(
            model_name='buildings',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildings',
            name='building_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('property_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11)),
                ('property_management_company', models.CharField(max_length=255)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiibs_backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('photos', models.URLField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiibs_backend.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiibs_backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiibs_backend.buildings')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to='jiibs_backend.users')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='jiibs_backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('neighbourhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighbourhood_name', models.CharField(max_length=255)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiibs_backend.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_no', models.CharField(max_length=255)),
                ('unit_size', models.CharField(max_length=255)),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('photos', models.URLField()),
                ('floor_plan', models.URLField()),
                ('status', models.CharField(max_length=255)),
                ('deals', models.TextField()),
                ('thumbnail', models.URLField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiibs_backend.buildings')),
            ],
        ),
    ]
