# Generated by Django 5.0 on 2023-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiibs_backend', '0003_alter_users_property_management_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
