# Generated by Django 5.0 on 2023-12-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiibs_backend', '0004_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.CharField(),
        ),
    ]
